server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace
#        2) da forma acima o log com o comando Hibernate é mostrado no padrão no console
#        3) já com o trace nós visualizamos os valores dos campos com os conteúdos (o que acredito não ser bom usar)